baseURL = "https://thugrabbit.github.io/"
languageCode = "zh-cn"
title = "ThugRabbit 's blog"

[params]
description = "Technology, project and daily idea"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"